### PR TITLE
Unit test trpc

### PR DESCRIPTION
**Pull request by AliMcG**
I have added Jest for unit testing of tRPC routes. This will allow us to start to separate some of the backend work from the UI as we will be able to unit test our routes without creating new components - to test routes in the UI.

It has also raised a interesting "bug" in prisma. The unit test for `shoppingLists.list` is currently returning all lists from the database. See this discussion: https://github.com/prisma/prisma/discussions/3386.

I think this highlights our need to develop more robust routes which can handle exceptions and errors.

### CODE REVIEW

**Review by webshuriken — COMMENTED** [review]
Good starting point

**Comment by webshuriken** [comment]
@AliMcG there is a merge conflict.

**Comment by AliMcG** [comment]
Merge conflict resolved.  One very random divergence with the package-lock - I accepted both versions and then ran `npm i` which seems to have fixed it.

**Comment by AliMcG** [comment]
[Unit tests for tRPC routes](https://trello.com/c/Gm0LdvOl/90-unit-tests-for-trpc-routes)

**Pull request merged**
